# Generated by Django 3.2.7 on 2021-10-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=100)),
                ('break_time', models.IntegerField(default=0)),
                ('daily_bonus', models.CharField(max_length=250)),
                ('dollar_for_instll', models.CharField(max_length=250)),
                ('how_to_work_link', models.CharField(max_length=250)),
                ('math_point', models.CharField(max_length=250)),
                ('watch_video_point', models.CharField(max_length=250)),
                ('need_help', models.CharField(max_length=250)),
                ('privacy_link', models.CharField(max_length=250)),
                ('rateus_link', models.CharField(max_length=250)),
                ('telegram_link', models.CharField(max_length=250)),
                ('wathdraw_notice', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.course')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.difficulty')),
            ],
        ),
    ]
